[paths]
audio_folder = "path/to/your/audio_files"
preprocess_s1_folder = "path/to/your/wav_converted_files"
preprocess_s2_folder = "path/to/your/resampled_files"
preprocess_s2_folder = "path/to/your/bit_depth_converted_files"
stem_separated_output_folder = "path/to/your/stem_separated_output_folder"